# Generated by Django 2.0.2 on 2018-03-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=6)),
                ('age', models.CharField(max_length=4)),
                ('agegroup', models.CharField(choices=[('pee-wee', 'PEE-WEE'), ('sub junior', 'SUB JUNIOR'), ('junior', 'JUNIOR'), ('senior', 'SENIOR'), ('senior black belt', 'SENIOR BLACK BELT')], default='senior', max_length=20)),
                ('weight', models.CharField(max_length=200)),
                ('weightcategory', models.CharField(choices=[('fin', 'FIN'), ('fly', 'FLY'), ('bantam', 'BANTAM'), ('feather', 'FEATHER'), ('light', 'LIGHT'), ('welter', 'WELTER'), ('light Middle', 'LIGHT MIDDLE'), ('middle', 'MIDDLE'), ('light Heavy', 'LIGHT HEAVY'), ('heavy', 'HEAVY')], default='fin', max_length=12)),
                ('PlayingFor', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
